### ISSUE TITLE
test_bug0

### ISSUE THREAD

**Issue by sercial** [PAU-Course-Selection/course-select#4]
The same email address can be logged in with a different password, which will prompt you with an incorrect password but you will still be able to log in.

**Comment by sercial** [comment]
Forgotten password button does not work

**Comment by sercial** [comment]
It's good to have requirements for the number of digits in the login interface, but would it be better to have requirements for the format of the password?

**Comment by Akomea** [comment]
Thank you for pointing out these security issues. I'm currently working on fixing them 😀

**Comment by Akomea** [comment]
Hey @sercial please review my pull request :)

**Comment by sercial** [comment]
I see the popup for trying to type multiple times in a short period of time, which is very interesting! But I still seem to be able to get to the next page with the wrong password. Instead of showing the user's specific email, it shows "user email"
